# Site settings
name: chjiyun.com
email: lijiun615@163.com
author: Ryan Lee
url: http://chjiyun.com/
resume_site: http://chjiyun.com/
github: https://github.com/chjiyun/
baseurl: ""
description: Actually, less is more!
meta_description: ryan lee;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 人常常有这种错觉，懒惰久了，稍微努力一下，就以为自己在拼命。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: chjiyun
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : youyan
    duoshuo:
        short_name : ryanlee
    disqus :
        short_name : ryanlee
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light